### ISSUE TITLE
TypeError: can't concat bytes to str, The version specified (b'v1.0.2.dev1-2-gff14bb0') is an invalid version

### ISSUE THREAD

**Issue by satvikmaker** [matt-hayden/faceswap#2]
I'm trying run this, but, having issues with it. It fails with the below error.

Ubuntu 16.04, Python 3.5, OpenCV 3.3

```
(cv) ubuntu@ip-172-31-28-204:~/faceswapwork/matt-hayden$ pip install -e faceswap/
Obtaining file:///home/ubuntu/faceswapwork/matt-hayden/faceswap
    Complete output from command python setup.py egg_info:
    
    Installed /home/ubuntu/faceswapwork/matt-hayden/faceswap/.eggs/setuptools_git-1.2-py3.5.egg
    running egg_info
    /home/ubuntu/.virtualenvs/cv/lib/python3.5/site-packages/setuptools/dist.py:350: UserWarning: The version specified (b'v1.0.2.dev1-2-gff14bb0') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
      "details." % self.metadata.version
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/ubuntu/faceswapwork/matt-hayden/faceswap/setup.py", line 24, in <module>
        setup_requires = [ "setuptools_git >= 1.2", ]
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 973, in run_command
        cmd_obj.ensure_finalized()
      File "/usr/lib/python3.5/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/home/ubuntu/.virtualenvs/cv/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 175, in finalize_options
        self.egg_version = self.tagged_version()
      File "/home/ubuntu/.virtualenvs/cv/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 265, in tagged_version
        return safe_version(version + self.vtags)
    TypeError: can't concat bytes to str
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/ubuntu/faceswapwork/matt-hayden/faceswap
```

**Comment by matt-hayden** [comment]
Looks like `setuptools_git` is giving me trouble. I'm seeing this in other packaging, too. I replaced `setup.py` and you should `git pull` inside `faceswap/` and retry the installation steps.

**Comment by H4wk-eye** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
shahzzzam, @stormrainer, @RonnyGiron, @lucasmachadorj, @jonathan-s, @pyadav, @daniel-chung, @naryad, @jorda0mega, @sebastianlzy, @millerm, @cseale, @taubizintel, @librepreso, @AlexanderCord, @frozeman, @stasnepo, @qbig, @brunoamaral, @willr
